import { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import SessionWrapper from "@/components/SessionWrapper";
import Navbar from "@/components/Navbar";
import { ToastContainer, Flip } from "react-toastify";
import { AppWrapper } from "@/context/index";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-black text-white bg-[linear-gradient(to_bottom,#0000,#200D42_34%,#4F21A1_65%,#A46EDB_82%)] font-inter">
        <SessionWrapper>
          <AppWrapper>
            <Navbar />
            <ToastContainer
              position="top-center"
              autoClose={1500}
              limit={1}
              hideProgressBar={false}
              newestOnTop={false}
              closeOnClick={false}
              rtl={false}
              pauseOnFocusLoss
              draggable
              pauseOnHover
              theme="colored"
              transition={Flip}
            />
            <main>{children}</main>
          </AppWrapper>
        </SessionWrapper>
      </body>
    </html>
  );
}